[build]
  command = "npm run build"
  publish = "/build" # Asegurate de que esta sea tu carpeta de salida real

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200